### ISSUE TITLE
Hello, I'd like to contribute to and join this organization!

### ISSUE THREAD

**Issue by ahcodes** [Uncodedtech/Join_Org#45]
Opened an issue as instructed in [here](https://github.com/Uncodedtech/Join_Org#join-the-organization).

I can help/contribute with HTML, CSS, and to a lesser extent with JavaScript and Python. Oh, and with documentation if that is needed as well!

**Comment by Surajv311** [comment]
Welcome @ahcodes !

**Comment by ahcodes** [comment]
Thank you!
